### ISSUE TITLE
M200

### ISSUE THREAD

**Issue by iddq** [abehterev/cdr_parse#1]
Can you please tell me what is M200?

**Comment by abehterev** [comment]
Hi. 
A russian pbx. 

Best regards,
Andrey Bekhterev

**Comment by iddq** [comment]
Does it have vendor-specific objects?

**Comment by abehterev** [comment]
No. It’s just cdr parser for a file which actually is text file with delimiters. 

Best regards,
Andrey Bekhterev

**Comment by iddq** [comment]
I see. I thought this is a 3GPP CDR parser. Thank you for the answers
